### ISSUE TITLE
Bug When Creating a geom_plot+geom_smooth+geom_abline graph

### ISSUE THREAD

**Issue by MainaJohnO** [IDEMSInternational/R-Instat#4332]
![capture](https://user-images.githubusercontent.com/32262789/34105678-57af0f20-e406-11e7-937f-1adf0095e2f9.PNG)
The attached bug pops up when trying to add an abline plot to a geom_plot + geom_smooth  plots using the father.son data set from the package UsingR. Hence we can not make a graph geom_plot+geom_smooth+geom_abline. For the geom_abline users need to type the intercept and slope values which is  not possible at the moment.

**Comment by dannyparsons** [comment]
This is a serious error box so thanks for finding this. 
But it's difficult to find the problem without seeing the R code or having clear instructions on how to do this. 
Can you recreate this? Then when you get the error press continue and copy and paste all the R code from the log window here.

In general the most helpful bug reporting is when anyone can reproduce the same thing you did from your message.

**Comment by ZIRANA11** [comment]
# Code generated by the dialog, Scatter Plot

father.son <- InstatDataObject$get_data_frame(data_name="father.son", stack_data=TRUE, id.vars="fheight", measure.vars="sheight")
scatterplot2 <- ggplot2::ggplot(data=father.son, mapping=ggplot2::aes(colour=variable, y=value, x=fheight)) + ggplot2::geom_boxplot() + theme_grey() + ggplot2::geom_smooth(method="lm", se=TRUE)
InstatDataObject$add_graph(data_name="father.son", graph=scatterplot2, graph_name="scatterplot2")
InstatDataObject$get_graphs(graph_name="scatterplot2", data_name="father.son")
rm(list=c("father.son", "scatterplot2"))


The above code is the one that produces the geom_point +geom_smooth. When we create this graph and go ahead to add the geom_abline it leads to the ealier attached bug

**Comment by ZIRANA11** [comment]
Once we have created the geom_point+geom_smooth and saved the graph. From the Describe menu>click on Use Graph.  On the dialog that appears we click on add to select the, when selected when we click ok the bug pops up
![capture_bug_whentrying to use the graph option so that we add the abline](https://user-images.githubusercontent.com/28622260/34255237-c23f986c-e660-11e7-9ab5-275f14006360.PNG)

**Comment by MainaJohnO** [comment]
Code generated by the dialog, Scatter Plot

father.son <- InstatDataObject$get_data_frame(data_name="father.son",
stack_data=TRUE, id.vars="fheight", measure.vars="sheight")
scatterplot2 <- ggplot2::ggplot(data=father.son,
mapping=ggplot2::aes(colour=variable, y=value, x=fheight)) +
ggplot2::geom_boxplot() + theme_grey() + ggplot2::geom_smooth(method="lm",
se=TRUE)
InstatDataObject$add_graph(data_name="father.son", graph=scatterplot2,
graph_name="scatterplot2")
InstatDataObject$get_graphs(graph_name="scatterplot2",
data_name="father.son")
rm(list=c("father.son", "scatterplot2"))

The above code is the one that produces the geom_point +geom_smooth. When
we create this graph and go ahead to add the geom_abline it leads to the
ealier attached bug

**Comment by MainaJohnO** [comment]
Once we create the geom_point+geom_smooth and save the graph, when we go
ahead to add the geom_abline the bug pops up.

From the Describe Menu we click on Use Graph, a dialog box appears we
select the graph we want to use and click add. When we click on to go ahead
and use the graph the bug pops up

**Comment by MainaJohnO** [comment]
# Code generated by the dialog, Use Graph

use_graph1 <- InstatDataObject$get_graphs(data_name="father.son",
graph_name="scatterplot1") + theme_grey()
InstatDataObject$add_graph(data_name="father.son", graph=use_graph1,
graph_name="use_graph1")
InstatDataObject$get_graphs(graph_name="use_graph1", data_name="father.son")
rm(use_graph1)

**Comment by dannyparsons** [comment]
Thanks for posting the code. 
@africanmathsinitiative/developers can someone look into this with @MainaJohnO?

**Comment by Patowhiz** [comment]
Where can I get the **father.son** dataset in R-Instant. @MainaJohnO  I can't find package **UsingR** in R-Instant.

**Comment by ZIRANA11** [comment]
Hello Patrick,
Go to R-Studio and install it then restart RInstat it will be there

**Comment by MainaJohnO** [comment]
Patrick for any package that you can not find in R-instat, you have to
first install it in Rstudio, then close your R-instant if it is open, then
when you restart R-instat it will be loaded and hence you can access it.

**Comment by Patowhiz** [comment]
@MainaJohnO  @ZIRANA11  Thanks.

**Comment by Patowhiz** [comment]
@MainaJohnO where/how  did you get/create the arguments passed to these functions ?

```
father.son <- InstatDataObject$get_data_frame(data_name="father.son",
stack_data=TRUE, id.vars="fheight", measure.vars="sheight")
```

```
scatterplot2 <- ggplot2::ggplot(data=father.son,
mapping=ggplot2::aes(colour=variable, y=value, x=fheight)) +
ggplot2::geom_boxplot() + theme_grey() + ggplot2::geom_smooth(method="lm",
se=TRUE)
```

**Comment by rdstern** [comment]
I notice this discussion stopped from here.  I am now documenting the scatterplot (geom_point), so checking if it is still a problem.  The book John used for the data, with package usingR, is interesting and should be added to R-Instat.  However, I tried what I interpet to be the analysis above, and don't have a problem now.  I note he used geom_boxplot, rather than geom_point, in the code above and that doesn't seem so sensible.  So I am closing this issue now.
