### ISSUE TITLE
Create a new dialog "Import from Postgres"

### ISSUE THREAD

**Issue by lilyclements** [IDEMSInternational/R-Instat#7828]
Create a new dialog "Import from Postgres"

This is related to the PLH work, and relevant for the GPI Retreat taking place on 12th September.

![image](https://user-images.githubusercontent.com/21180424/188288008-026a87f5-529c-4326-8cc9-440a092e6321.png)

The "Import from Postgres" dialog has four labels and four input boxes at the start:

* Username (takes a string)
* Database name (takes a string)
* Host (takes a string)
* Port (takes numeric values)

There is then a button "Get Data".

This button opens a new dialog, very similar to what happens in the "Import from ODK" dialog, where the user writes in a password.
Upon pressing OK, the following R code is run:

```plh_con <- DBI::dbConnect(RPostgres::Postgres(), user = "USERNAME", dbname = "DATABASE NAME", host = "HOST", port = PORTNUMBER, pass = "VALUE IN NEW DIALOG")```

This code should not display in the output window, because we do not want the password to be visible. 

Once this code is run, the following R code runs to populate the drop down box (like in the Import from ODK dialog)
```DBI::dbListTables(plh_con)```
This gives a list of the data set names that can be accessed.

Upon pressing OK, the following code runs to import the data:

```
postgresr::get_postgres_data(site = plh_con, name = "VALUE IN DROPDOWN")
```

**Comment by Patowhiz** [comment]
This issue relates to issue #4620. I strongly suggest that instead of a custom dialog for PLH or Postgress import, we take this chance to design and implement it as explained in https://github.com/africanmathsinitiative/R-Instat/issues/4620#issuecomment-1238180394 of that issue.
