### ISSUE TITLE
The Plot sub-dialog facets has poor memory!

### ISSUE THREAD

**Issue by rdstern** [IDEMSInternational/R-Instat#8763]
I was using it from the boxplot dialog - I don't know if that is relevant.  I was also using 2 facet variables.  When I return to the sub-dialog it has remembered that there are facets, but not the variables used.

I used the `amis` data from the `boot` package.  Made the 3 variables into factors.  Then used `pair`  as the factor on the main dialog and period and warning as the 2 facet variables:

![image](https://github.com/IDEMSInternational/R-Instat/assets/11226469/3a582911-7e38-41f4-87e9-54cc67361933)

**Comment by MeSophie** [comment]
This issue is solved in #8773
