### ISSUE TITLE
Import data not working after getting the last update

### ISSUE THREAD

**Issue by N-thony** [IDEMSInternational/R-Instat#8780]
@rdstern @Vitalis95 @MeSophie I get this error below after updating my local master branch. Can you confirm if you get the same error?
![image](https://github.com/IDEMSInternational/R-Instat/assets/68591383/aa59f408-aaac-4e4e-b5fd-a4815baa4429)

**Comment by MeSophie** [comment]
@N-thony It is the same from my side.
![image](https://github.com/IDEMSInternational/R-Instat/assets/106779233/3f94c8e9-83ce-4fbd-8554-e183ebdc846f)

**Comment by derekagorhom** [comment]
@N-thony below is a screenshot from when PR #8708 was merged. as you can see there was no `WB_evanporation` function at that time there, so this could not have been cause (perhaps merge conflicts).

![image](https://github.com/IDEMSInternational/R-Instat/assets/76208189/3ec364a8-f88a-4498-9d7f-8fbe05f577a2)

**Comment by MeSophie** [comment]
![image](https://github.com/IDEMSInternational/R-Instat/assets/106779233/c024ae50-7943-4734-a8be-43d2c8c2e450)

@N-thony Yes It is coming from the last change made by Lily.

![image](https://github.com/IDEMSInternational/R-Instat/assets/106779233/baf9268d-21b8-444d-802a-52d257884393)
