### ISSUE TITLE
Add four new keys to the Calculator

### ISSUE THREAD

**Issue by rdstern** [IDEMSInternational/R-Instat#8820]
I am concerned that we missed these, so @lilyclements could you first confirmthat we do need them!
If so, then @Fidel365 I suggest you could enjoy adding them.  I hope it will be easy.  

The screenshot shows an example:

![image](https://github.com/IDEMSInternational/R-Instat/assets/11226469/515d51cb-8e0d-480a-8f8f-fdbfff49d094)

Get the murders data from the dslabs package.  Then x is the murder rate per 100,000, calculated by `total/population *100000`

So what we need is 4 new keys.  Move the last line of the first block down, and insert keys with labels
which.max, where.max, which.min, where.min.

`Which` is just the function , `which.max(  )`, similarly for `which.min( )`.
`Where` is then the function `<space> [which.max(  )] `with the cursor right at the starting space, ready for that first variable, as shown in the figure.

Tool tip for which.max "Row number of the maximum value.  So which.max(c(4,3,10,1,2)) is 3".
Similarly "Row number of the minimum value.  So which.min(c(4,3,10,1,2)) is 4"
For where.max: "Value of a variable at the which.max position.  So for c("a","b","c","d","e"), is "c", for the data in which.max tooltip."
For where.min "Value of a variable at the which.min position.  So for c("a","b","c","d","e"), is "d", for the data in which.min tooltip"

**Comment by lilyclements** [comment]
@rdstern this sounds sensible.

We have `which` under `Logical and Symbols` currently, but no reason why we can't have it twice? The tooltip there is "which gives the indices of a logical variable. For example which(11:15>13) gives 4, 5. Note the result is usually not the same length as the original variable." - just adding this here in case we wanted to alter one or the other for consistency between them
