### ISSUE TITLE
Having multiple tables (presumably html) in the output window?

### ISSUE THREAD

**Issue by rdstern** [IDEMSInternational/R-Instat#8855]
@Patowhiz I am trying to redo the Describe > Two/Three Variable dialog, and I keep coming up agianst the limit that we can currently have only a single (html) table, at a time in the output window.  The dialog produces a different type of summary for each of the combinations (2 variables) or cat/cat, (frequency tables) cat/num, (summary tables) num/cat (ANOVA) and num/num (ANOVA).  

The ANOVA options are very happy with multiple tables.  The frequency and summary tables are not. 

I wonder how much work it is to change that?  I assume it is the same limitation if we produce an rtf output?

Ideally we could havce multiple html, but otherwise could the (multiple) tables more easily be non-html ones?  

If this is realoly difficult I wonder - maybe @lilyclements could advise, - whether we could quickly only use gt for the output, when there is a single variable in the first control, and not bother with it, if there's more than one?  

I just want to make sure we have looked at all the options, before spending too much time on changes to this dialog, simply to fit within current output restrictions?

**Comment by Patowhiz** [comment]
@rdstern currently we still don't support list output objects. To support them, we may have to implement code that iterates through the contents of the list object checking on the type and format supported so that we can create a single file or multiple files for display. This requires improving what currently exists. 

As a temporary implementation, we could decide to send list output objects to R which will then use the default viewer. This means they won't go the output window. This will require minimal changes to our current architecture.

**Comment by rdstern** [comment]
@Patowhiz do we use the R default viewer for anything yet?  That sounds a really nice option to explore?  If it is good enough for ordinary R, then it is good enough for me.  Is this fgor you to specify and then @N-thony to implement?  Or can you do an initial run quickly?

**Comment by rdstern** [comment]
@Patowhiz and @N-thony if I understand the information above correctly then a quick temporary solution would be for R-Instat to detect whether there single or multiple HTML files have been generated.  If single, then the results go to the output window, and if multiple, they go to a browser.

Patrick, am I correct that this would be easy to do?  If so, I'd be very happy with that as our 2024 solution!  We rarely generate multiple html and the help can explain how a user can avoid them, if they wish.

**Comment by Patowhiz** [comment]
@rdstern yes! At the R level, a check could be added to check the type of the output object. If the object is of a class that produces multiple outputs, then we just let R to display it with the default browser. That can be done under the `view_object_data` R function.

**Comment by Patowhiz** [comment]
@N-thony I'm not sure on the precise execution details. I'm happy to let you explore on the implementation. Then we could check and test.

**Comment by Patowhiz** [comment]
@N-thony I'm a bit confused with your comment. Kindly expound a bit. What is it that you think has an issue in the `gt` package?   Does it prevent the output from going to the default browser?

**Comment by Patowhiz** [comment]
@N-thony thanks for clarifying. 
@rdstern the problem has been identified by @N-thony . Back to you both.
