### ISSUE TITLE
Add `gh` package into R-Instat

### ISSUE THREAD

**Issue by lilyclements** [IDEMSInternational/R-Instat#8871]
This is a small package which is just used to access bits from Github within R-Instat. On @Vitalis95's PR #8858 we use the `gh` package.

Can the `gh` package be added into R-Instat?

@Fidel365 I think you added the package in last time - do you know how to do this? THanks!

**Comment by Fidel365** [comment]
@lilyclements , I can see the gh package is already installed in R-instat?
![image_2024_03_12T10_03_32_909Z](https://github.com/IDEMSInternational/R-Instat/assets/107605960/f5b8acb2-f4cf-4925-a837-5bb0620c6163)

**Comment by lilyclements** [comment]
@Fidel365 good point - you're right! I should have most definitely checked this before setting up the issue... My bad. Thanks for checking
