### ISSUE TITLE
Resize "Select Day of Year Range" box in Start of Rains Dialogue

### ISSUE THREAD

**Issue by jkmusyoka** [IDEMSInternational/R-Instat#8975]
@N-thony this is a minor cosmetic issue that I hope is a small and quick fix. The box has a big empty space that should be reduced/removed to improve its appearance.

![image](https://github.com/IDEMSInternational/R-Instat/assets/8112611/9e116ad8-43a3-40bf-bc67-5b2a3073a1fc)

**Comment by Fidel365** [comment]
On second thoughts about this, maybe we should have variable day as default, so that the dialog looks a bit nicer on first load, this is a question for @rdstern
