### ISSUE TITLE
Add a Secondary Axis to the Y-axis as Well as the X-axis?

### ISSUE THREAD

**Issue by MeSophie** [IDEMSInternational/R-Instat#8982]
@rdstern It would be good to add the Secondary y axis to the y-axis in plot options - this will help with the ordinary climograph. And maybe some other graphs?
![image](https://github.com/IDEMSInternational/R-Instat/assets/106779233/b952988c-9965-4565-96a6-5ce956d791ef)

**Comment by rdstern** [comment]
@MeSophie I absolutely agree, but you are starting to worry me slightly!  You see I forget things so easily, and put this down partly to my advancing years.

But here is the secondary y-axis, that was added - and very nicely - by Sophie.  And I think you know her very well eh?!

![image](https://github.com/IDEMSInternational/R-Instat/assets/11226469/835dee22-2594-4b7f-a7df-7ee35ebff723)

**Comment by MeSophie** [comment]
Thank you @rdstern. I had just added for the x-axis certainly another colleague did it after me. This reminds me that my branch hasn't also been up to date for a while. I'm going to close this issue.
