### ISSUE TITLE
REturning presentation of roman to the calculator

### ISSUE THREAD

**Issue by rdstern** [IDEMSInternational/R-Instat#9005]
@Fidel365 I think - except for presenting Roman numerals in the reogrid (that may need discussion with @N-thony) that the improvements to the calculator (again except for the great addition to scalars by Antoine) are now done.

There are 9 open issues that relate to the calculator, namely
#8940 
#8931 
#8925 
#8918 
#8905 
#8904 
#8902 
#8884 
#8820 

I think they may all be done and hence could be closed.  Could you please check, report and close - or get @N-thony to close if you are not sure.

Thanks

Roger

**Comment by Fidel365** [comment]
@rdstern I have closed all execept issue #8931 because of the issue with Roman numbers which is still in progress. So this can be closed when you are happy.

**Comment by rdstern** [comment]
@Fidel365 that's great.  Please also remember the item of adding the functions file (for the functions keyboard) into the R-Instat library.
