### ISSUE TITLE
Improvements to the Climsoft Export dialog

### ISSUE THREAD

**Issue by rdstern** [IDEMSInternational/R-Instat#9095]
Here is the current dialog:

![image](https://github.com/user-attachments/assets/ba967d14-9f77-4d51-94c2-36fadea66b1b)

My suggested changes are as follows:  
They are minor, so I hope can be undertaken quickly by @Vitalis95, but @Patowhiz needs to check and correct the suggestions below, before Vitalis starts.

a) At the top there are our "usual" radio buttons with Daily, Hourly being the 2 options.  Hourly is disabled for now.
b) Under Station  there is another single receiver with `Station ID ` as the label.  (We are deleting the Level reciever, so maybe that can be moved and used.
c) The Date and Hour remain as now.  (At least for now.)
d) The Level receiver isn't needed.

In the code the date and hour need to be combined to produce a date-time variable in the right shape.  @Patowhiz will specify.

(In our discussion Patrick mentioned that Climsoft can perhaps also be improved, but we need - for now - to be able to work with the existing version.)

In our discussions we recognise 2 different situations - there may be a third, see below:
a) Data may start in Climsoft and may then a subset corrected and returned.  This could simply adapt the file imported from Climsoft.  It can be saved as a csv and it automatically the right shape to be imported into Climsoft.
b) Data may start elsewhere.  It will be defined as climatic (if daily).  This will then be exported via the Export dialog.
c) Other Climatic management systems will also have importing of csv data.  In the future they may use the same dialog.

**Comment by Patowhiz** [comment]
I suggest the resulting data frame or file from this dialog to have the following columns

**Station Id (station_id)** - These should be ids that are in the Climsoft database.
**Date and Time (date_time)** - Should be in the format **YYYY MM DD HH:SS**
**Element columns** - Columns that represent elements. Column names should be recognised element abbreviations. Can be single or element

Note, unlike before, the dialog doesn't need to stack the elements. Should leave them as unstacked.

**Comment by Vitalis95** [comment]
> I suggest the resulting data frame or file from this dialog to have the following columns
> 
> **Station Id (station_id)** - These should be ids that are in the Climsoft database. **Date and Time (date_time)** - Should be in the format **YYYY MM DD HH:SS** **Element columns** - Columns that represent elements. Column names should be recognised element abbreviations. Can be single or element
> 
> Note, unlike before, the dialog doesn't need to stack the elements. Should leave them as unstacked.

Sorry @Patowhiz , what do you mean by the elements should left unstacked?

**Comment by Patowhiz** [comment]
@Vitalis95 I meant the columns that you select to add in the multiple receiver.

@rdstern I investigated this with Marcellin and realised that if you have your data defined as climatic in R-Instat, then it is already in a format that is ingestible by Climsoft (we will fix the subtle bugs on the Climsoft end)

The main missing field in the define climatic dialog is the hour. If we can add the hour at that level, then we may not need this dialog for daily and hourly data.

**Comment by Vitalis95** [comment]
> @Vitalis95 I meant the columns that you select to add in the multiple receiver.
> 
> @rdstern I investigated this with Marcellin and realised that if you have your data defined as climatic in R-Instat, then it is already in a format that is ingestible by Climsoft (we will fix the subtle bugs on the Climsoft end)
> 
> The main missing field in the define climatic dialog is the hour. If we can add the hour at that level, then we may not need this dialog for daily and hourly data.

@rdstern @Patowhiz , should I proceed with working on the dialog or we just add hour field in the Define Climatic dialog?
