### ISSUE TITLE
R-Instat, probably reogrid has a problem with shape files

### ISSUE THREAD

**Issue by rdstern** [IDEMSInternational/R-Instat#9160]
The `Climatic > File > Import and tidy Shape files` is used routinely for our climatic mapping work.

![image](https://github.com/user-attachments/assets/a4e285e3-6825-487f-b85e-5f748ac0b987)

Here is an example of data from Zimbabwe.  I found the problem with similar data from Bangladesh.  I think it is with all the shape files, at least those from gadm.

![image](https://github.com/user-attachments/assets/26e9eda4-34a1-4cce-b5b9-e3e785f5c255)

Note that this is a challenging type of file for reogrid to be able to handle.  The one shown only has 91 rows, but the geometry variable is sufficiently large that the data frame is over 5 mbytes.  (The one where I found the problem was over 100 mbytes.)

a) The first problem - perhaps minor - is that R-Instat now runs slowly, and I assume this may be to do with refreshing the reogrid.  For example making (say) NAME_1 into a factor takes over 1 minute on the Bangladesh data.

b) So I then tried to do something about the geometry variable.  I tried right-click and delete, then right-click and rename.  Each time I get this error message and it then closes the data frame.  Other data frames stay open.

![image](https://github.com/user-attachments/assets/fbed2e02-b26d-4639-aeb6-2a054f5704d5)

 @N-thony I wonder what can be done.  I note it adds special types the the metadata.  I fon't need to be able to dit, or do anything with the contents of the geometry variable.  It works, in that the maps are drawn.  I would just like reogrid to handle the data frame better - and also not throw me out of R-Instat.

I wonder if this problem may need some @ChrisMarsh82 advice?

**Comment by Patowhiz** [comment]
@rdstern @N-thony could you do these tests in R Studio. Whenever I want to know whether things are slow in the front end, I conduct the tests in R Studio, by running line by line the log file.
Reogrid get's a limited number of rows and operations like renaming are done on the R side then refreshed in the reogrid by reading from R.
@N-thony I think you can check or delegate someone to check on why the rename dialog has the bug.

Personally I have an issue with how ingestion and usage of  shape files was conceptualised as ordinary data frames. I think shape files are not meant to be read or displayed as tables, I treat them as Geojson, which again are meant for applications to use in drawing maps not human users. Unfortunately I haven't thought of how else we could treat them in R-Instat and still be able to use them in dialogs. In the meantime, I would propose doing much of the processing (renaming and changing of factors etc) during the import itself, so that operations can be done outside of the data book.

**Comment by rdstern** [comment]
@Patowhiz and @N-thony I strongly suggest you may go round in circles involving the whole team in this fix.  The error message implies to me that it is probably ok in R and hence RStudio.  I can picture that the geometry variable might cause problems for reogrisd, because it is so complex.  I wonder, instead, if @ChrisMarsh82 could look at this problem?  In the variable it isn't a rewname problem.  I get just the same error if I try to delete the variable.  I suspect doing anything to that variable will trigger the problem.

And, I assume they way reogrid handles that variable is linked to the clear slowing down on R-Instat when doing simple operations on other variables.  Like changing a name variable into a factor.  Please note @Patowhiz that I don't case particularly if it is a factor or a character variable.  I care that it seems that operations on that data frame are unreasonably slow - whatever they are.  And operations on that variable are both impossible and throw the user out of that data frame.  I don't have any other operation I have found that does this.

On the positive side, I am really impressed with the ease with which we seem to be able to enter these data, and their neat use (that still works) in drawing maps.

**Comment by Patowhiz** [comment]
@rdstern thanks for the details. And as you say, I'm happy for @ChrisMarsh82 to look at the problem.

**Comment by ChrisMarsh82** [comment]
@N-thony Not sure if I fully understand this but if we can bring back the value fine in the dataframe and it is just reogrid causing issues then could we set up reogrid to show '[BLOB]' (or some equivalent) and not ever attempt to show values for that datatype. 
This would hopefully mean dialogs still work fine as they will be using the dataframe value and not the value in reogrid. 
We could even have a click on the cell to bring a pop up memobox with the value in if needed.

Can you check that its reogrid causing the issue and not the dataframe. If the dataframe is also causing issues we could do something similar where we don't bring the value back for the column but this would get more complicated when it comes to the dialogs that use the field.

**Comment by ChrisMarsh82** [comment]
@N-thony screenshot looks good. Does this solve the speed issues? Are you able to add a double click to the cell so users can see the info within the multipolygon? 
You mentioned rename doesn't work is there any other functions that we have issues with on multipolygon, Can you list them all so issues can be created.

**Comment by rdstern** [comment]
@ChrisMarsh82 and @N-thony I first found the same problem when I tried to delete the variable.  Then I moved to rename.  I haven't tried re-ordering, or duplicate column.

**Comment by rdstern** [comment]
In e-siac we are using shape files today.  So I am noticing the problem again.

Luckily the biggest shape file has just 115 rows.  But it is still clear that this issue needs to be addressed.  @derekagorhom I see you were allocated this a few weeks ago.  I am not clear whether you will be able to proceed, but good for you to look quickly, and maybe pass the problem back to (or get help from) @N-thony if you don't know how to approach it.

It is not urgent, for the forthcoming version, but would be good to have it by the end of 2024.

**Comment by rdstern** [comment]
Thanks @N-thony for taking this over.

I add a further problem with these files in reogrid athat came up earlier.  For e-siac I saved the shape and data files together.  When I re-open the shape file it is formatted badly in reogrid.  Note it works and we rarely want to change anything in  the file.  Might we for example turn of editing as an option - so - like the r-viewer you can use it, but not change it - at least in reogrid?
[Climsoft stations.zip](https://github.com/user-attachments/files/17879077/Climsoft.stations.zip)

**Comment by rdstern** [comment]
@N-thony I would be happy with read only, as long as it solves the display and speed problems.  Except I would still like Filter to work!  That's important to be able to draw maps of part of the country.

**Comment by rdstern** [comment]
@N-thony I'm hoping something can be done on this issue for the enxt release.  That's because the current (I assume) reogrid implementation seems to slow R-Instat down considerably, particularly when there are many rows.  As there are for gadm in Bangladesh.  So I chose to ignore mapping there - which is a shame.

I note also that when saved in an rds file it comes back into the data book with each row using a whole screen.

I assume it is the geometry variable that is responsible.  

I have lots of alternative possibilities and suggest discussions with Chris may be useful.  

a) Maybe that variable could be made read-only, and that would be a solution?
b) Maybe the whole data frame could be read only, and that would work?  As long as I can still filter.
c) I don't even need it to be visible!  As long as the metadata is visible, so we know the columns.  Maybe just the column names are visible with a message, saying Sorry, data can't be shown here.  Use the column metadata or R-viewer for details.
d) If it can't be shown, could we repeat the metadata there instead?

Good luck
