### ISSUE TITLE
Regression in Version 0.7.21-  correlations no longer work, because GGally is no longer installed?

### ISSUE THREAD

**Issue by rdstern** [IDEMSInternational/R-Instat#9169]
@N-thony the problem in Version 21 is more general - I think.  GGally is missing in Version 21, and was there in version 20.  I also counted the number of packages starting with gg in R-Instat in Version 20 compared to 21.  There are 22 in Version 21 compared with 27 in version 20.  So, something more general has chasnged to leave out these packages.

I'll download the new Version 21, I've just seen, and check there also.

@N-thony If you open, I assume any file, say survey or dodoma and try Describe > Two/Three Variables > Correlations, with an options and plot, it now gives a fault and says that GGally is not installed.

Note it works in Version 0.7.20.  
a) This is worrying, in a number of ways.  First please add it, so the correlations works again.
b) Do you know any reason why just this package should have been omitted?  I am concerned that other packages may also be missing?
c) I tried to install the package - after all that's what should now be easier.  That failed too.

@jkmusyoka this is a warning for next week in Eswatinini.  We should check more before your workshop.

**Comment by jkmusyoka** [comment]
@rdstern I was waiting for the new installer to test more for next week. I am glad its ready so I will also download and check as well. I hope we can do quick fixes before Friday incase there are issues

**Comment by rdstern** [comment]
Just to reply here that you are right, but small adjustments to your commands are needed.  

```
library(remotes)
remotes::install_version("broom.helpers", version = "1.15.0")
remotes::install_version("ggstats", version = "0.6.0")
```

**Comment by rdstern** [comment]
This is solved with the updating of R, so closed
