### ISSUE TITLE
R-Instat not connecting with R

### ISSUE THREAD

**Issue by rachelkg** [IDEMSInternational/R-Instat#9313]
Hello @N-thony and @rdstern, 

I am having trouble getting my R-Instat to work. I am trying to run it through Visual Studio so that I can use the version with the most up to date changes. I get this message:
![2024-12-16_14-39-35](https://github.com/user-attachments/assets/49837564-71cc-42d6-8957-9fae785f2297)

I downloaded the newest version of R and installed it. Deleted all my old versions of R. But I still get this message. it seems like it is not communicating with R correctly. 

It all works fine when I use R-Instat 0.8.0. Antoine, any idea what I am doing wrong or how to fix it? 

thanks, 

Rachel

**Comment by rachelkg** [comment]
Thanks @N-thony. In my case setting the CPU to x64 in Visual Studio solved the problem, it was originally set to Any CPU.

Best, 

Rachel

**Comment by rdstern** [comment]
I'm closing as it seems solved
